name: Main Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: provide-io
      - name: Install dependencies
        working-directory: provide-io/pyvider-hcl
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install uv
          uv sync --all-extras
      - name: Install project with dev dependencies
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv pip install -e .[dev]
          pip install -e provide-io/pyvider-cty
      - name: Lint and Format
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv run ruff check .
          uv run ruff format . --check

  type-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: provide-io
      - name: Install dependencies
        working-directory: provide-io/pyvider-hcl
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install uv
          uv sync --all-extras
      - name: Install project with dev dependencies
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv pip install -e .[dev]
      - name: Type Check
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv run mypy src

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
        with:
          path: provide-io
      - name: Set up Python ${{ matrix.python-version }}
        working-directory: provide-io/pyvider-hcl
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install uv
      - name: Install dependencies
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv sync --all-extras
      - name: Install project with dev dependencies
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv pip install -e .[dev]
      - name: Test
        working-directory: provide-io/pyvider-hcl
        run: |
          source .venv/bin/activate
          uv run pytest